project:
  type: website

website:
  # site-url: https://www.matanhakim.org
  description: "Matan Hakim's personal website"
  image: profile.jpg
  favicon: profile.jpg
  twitter-card: true
  open-graph: true
  navbar:
    title: "Matan Hakim - Policy Data Scientist"
    right:
      - text: "About"
        file: index.qmd
      - text: "Blog"
        file: posts.qmd
      - text: "CV"
        file: cv.qmd
      - icon: github
        href: https://github.com/matanhakim
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/matanhakim.bsky.social
      - icon: mastodon
        href: https://fosstodon.org/@matanhakim
        rel: me
      - text: "{{< iconify simple-icons:orcid >}}"
        href: https://orcid.org/0009-0002-9372-8975
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
execute:
  freeze: auto